mybatis:
  config-location: classpath:db/mybatis/config.xml

spring:
  application:
    name: wechatshop-main
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wechatshop?useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081

wechatshop:
  orderservice:
    version: 0.0.1
    url: ""
  redis:
    host: 127.0.0.1:6379

dubbo:
  registry:
    address: zookeeper://localhost:2181
#  consumer:
#    check: false

