spring:
  application:
    name: wechatshop-main
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shop_order?useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

mybatis:
  config-location: classpath:db/mybatis/config.xml

wechatshop:
  orderservice:
    version: 0.0.1

dubbo:
  scan:
    base-packages: com.order.service
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: wechatshop-order
  url: 127.0.0.1
  protocol:
    name: dubbo