#mybatis:
#  config-location: classpath:db/mybatis/config.xml
#
#spring:
#  application:
#    name: wechatshop
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.104:3307/wechatshop?useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
#    username: root
#    password: 123456
#  main:
#    allow-bean-definition-overriding: true
#
#wechatshop:
#  orderservice:
#    version: 1.0.0
#    url: ""
#  redis:
#    host: 192.168.0.104:6379
#dubbo:
#  scan:
#    base-packages: com.wechatshop.orderservice
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: zookeeper://192.168.0.104:2181
#
